<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Database\Seeder;

/*
 | Каталог оборудования.
 |
 | Данные разобраны из официального дилерского прайс-листа
 | ООО «Каримали Рус» от 26.05.2026.
 |
 | ВАЖНО: в каталог выгружена только розничная цена (РРЦ) — этого требует
 | сам прайс. Дилерские цены в базу не попадают.
 |
 | Изображения взяты из того же прайса и лежат в public/assets/shop.
 */
class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            ['slug' => 'rozhkovye-kofemashiny', 'title' => 'Традиционные рожковые кофемашины',
             'description' => 'Профессиональные эспрессо-машины для кофеен и баров.', 'sort' => 10],
            ['slug' => 'superavtomaty', 'title' => 'Суперавтоматические кофемашины',
             'description' => 'Автоматические кофемашины для офисов, отелей и точек самообслуживания.', 'sort' => 20],
            ['slug' => 'kofemolki', 'title' => 'Кофемолки',
             'description' => 'Профессиональные кофемолки с плоскими жерновами.', 'sort' => 30],
            ['slug' => 'aksessuary', 'title' => 'Аксессуары и расходники',
             'description' => 'Холодильники, нагреватели чашек, чистящие средства.', 'sort' => 40],
        ];

        $ids = [];
        foreach ($categories as $c) {
            $ids[$c['slug']] = ProductCategory::updateOrCreate(['slug' => $c['slug']], $c)->id;
        }

        $products = [
            ['slug' => 'nimble-e1-black-ni-e01-h-01-nl', 'sku' => 'NI-E01-H-01-NL',
             'brand' => 'Carimali', 'title' => 'NIMBLE E1 BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 230000,
             'availability' => 'in_stock', 'stock' => 37,
             'image' => '/assets/shop/nimble-e1-black-ni-e01-h-01-nl.jpg', 'sort' => 10,
             'variant_group' => NULL, 'color' => 'Чёрный',
             'summary' => '1 группа, автомат, высокие группы, объем бойлера 4 литра, цвет черный c задней зеркальной панелью, PID контроль, система предсмачивания',
             'description' => '1 группа, автомат, высокие группы, объем бойлера 4 литра, цвет черный c задней зеркальной панелью, PID контроль, система предсмачивания'],
            ['slug' => 'nimble-e2-black-with-light-ni-e02-h-02', 'sku' => 'NI-E02-H-02',
             'brand' => 'Carimali', 'title' => 'NIMBLE E2 BLACK WITH LIGHT',
             'category' => 'rozhkovye-kofemashiny', 'price' => 295000,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/nimble-e2-black-with-light-ni-e02-h-02.jpg', 'sort' => 20,
             'variant_group' => 'nimble-e2', 'color' => 'Чёрный, с подсветкой',
             'summary' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет черный с задней зеркальной панелью, экран настройки температур, PID контроль, система предсмачивания, двойной маном',
             'description' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет черный с задней зеркальной панелью, экран настройки температур, PID контроль, система предсмачивания, двойной манометр (в комплекте 2 холдера: 1 двойной на 18 г и 1 одинарный на 7 г)'],
            ['slug' => 'nimble-e2-black-ni-e02-h-02-nl', 'sku' => 'NI-E02-H-02-NL',
             'brand' => 'Carimali', 'title' => 'NIMBLE E2 BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 295000,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/nimble-e2-black-ni-e02-h-02-nl.jpg', 'sort' => 30,
             'variant_group' => 'nimble-e2', 'color' => 'Чёрный',
             'summary' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет черный с задней прозрачной панелью, экран настройки температур, PID контроль, система предсмачивания, двойной маном',
             'description' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет черный с задней прозрачной панелью, экран настройки температур, PID контроль, система предсмачивания, двойной манометр (в комплекте 2 холдера: 1 двойной на 18 г и 1 одинарный на 7 г)'],
            ['slug' => 'nimble-e2-white-with-light-ni-e02-h-02-white', 'sku' => 'NI-E02-H-02 -WHITE',
             'brand' => 'Carimali', 'title' => 'NIMBLE E2 WHITE WITH LIGHT',
             'category' => 'rozhkovye-kofemashiny', 'price' => 295000,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/nimble-e2-white-with-light-ni-e02-h-02-white.jpg', 'sort' => 40,
             'variant_group' => 'nimble-e2', 'color' => 'Белый, с подсветкой',
             'summary' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет белый с задней прозрачной панелью, экран настройки температур, PID контроль, система предсмачивания, двойной маноме',
             'description' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет белый с задней прозрачной панелью, экран настройки температур, PID контроль, система предсмачивания, двойной манометр (в комплекте 2 холдера: 1 двойной на 18 г и 1 одинарный на 7 г)'],
            ['slug' => 'nimble-e2-redwith-light-ni-e02-h-02-red', 'sku' => 'NI-E02-H-02-RED',
             'brand' => 'Carimali', 'title' => 'NIMBLE E2 RED WITH LIGHT',
             'category' => 'rozhkovye-kofemashiny', 'price' => 295000,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/nimble-e2-redwith-light-ni-e02-h-02-red.jpg', 'sort' => 50,
             'variant_group' => 'nimble-e2', 'color' => 'Красный, с подсветкой',
             'summary' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет красный с задней прозрачной панелью, экран настройки температур, PID контроль, система предсмачивания, двойной мано',
             'description' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет красный с задней прозрачной панелью, экран настройки температур, PID контроль, система предсмачивания, двойной манометр (в комплекте 2 холдера: 1 двойной на 18 г и 1 одинарный на 7 г)'],
            ['slug' => 'nimble-e2-yellow-with-light-ni-e02-h-02-yellow', 'sku' => 'NI-E02-H-02-YELLOW',
             'brand' => 'Carimali', 'title' => 'NIMBLE E2 YELLOW WITH LIGHT',
             'category' => 'rozhkovye-kofemashiny', 'price' => 295000,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/nimble-e2-yellow-with-light-ni-e02-h-02-yellow.jpg', 'sort' => 60,
             'variant_group' => 'nimble-e2', 'color' => 'Жёлтый, с подсветкой',
             'summary' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет жёлтый с задней прозрачной панелью, экран настройки температур, PID контроль, система предсмачивания, двойной маном',
             'description' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет жёлтый с задней прозрачной панелью, экран настройки температур, PID контроль, система предсмачивания, двойной манометр (в комплекте 2 холдера: 1 двойной на 18 г и 1 одинарный на 7 г)'],
            ['slug' => 'nimble-e2-bluewith-light-ni-e02-h-02-blue', 'sku' => 'NI-E02-H-02-BLUE',
             'brand' => 'Carimali', 'title' => 'NIMBLE E2 BLUE WITH LIGHT',
             'category' => 'rozhkovye-kofemashiny', 'price' => 295000,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/nimble-e2-bluewith-light-ni-e02-h-02-blue.jpg', 'sort' => 70,
             'variant_group' => 'nimble-e2', 'color' => 'Синий, с подсветкой',
             'summary' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет синий с задней прозрачной панелью, экран настройки температур, PID контроль, система предсмачивания, двойной маноме',
             'description' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет синий с задней прозрачной панелью, экран настройки температур, PID контроль, система предсмачивания, двойной манометр (в комплекте 2 холдера: 1 двойной на 18 г и 1 одинарный на 7 г)'],
            ['slug' => 'glow-e2-black-gl-e2-b', 'sku' => 'GL-E2-B',
             'brand' => 'Carimali', 'title' => 'GLOW E2 BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 400000,
             'availability' => 'in_stock', 'stock' => 31,
             'image' => '/assets/shop/glow-e2-black-gl-e2-b.png', 'sort' => 80,
             'variant_group' => 'glow-e2', 'color' => 'Чёрный',
             'summary' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет черный, таймер, подсветка групп, экран настройки температур, PID контроль, система предсмачивания, двойной манометр',
             'description' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет черный, таймер, подсветка групп, экран настройки температур, PID контроль, система предсмачивания, двойной манометр'],
            ['slug' => 'glow-e2-black-stainless-gl-e2-b-s', 'sku' => 'GL-E2-B&S',
             'brand' => 'Carimali', 'title' => 'GLOW E2 BLACK&STAINLESS',
             'category' => 'rozhkovye-kofemashiny', 'price' => 400000,
             'availability' => 'in_stock', 'stock' => 20,
             'image' => '/assets/shop/glow-e2-black-stainless-gl-e2-b-s.png', 'sort' => 90,
             'variant_group' => 'glow-e2', 'color' => 'Чёрный со сталью',
             'summary' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет черный + зеркальные панели корпуса, таймер, подсветка групп, экран настройки температур, PID контроль, система пред',
             'description' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет черный + зеркальные панели корпуса, таймер, подсветка групп, экран настройки температур, PID контроль, система предсмачивания, двойной манометр'],
            ['slug' => 'glow-e2-white-gl-e2-w', 'sku' => 'GL-E2-W',
             'brand' => 'Carimali', 'title' => 'GLOW E2 WHITE',
             'category' => 'rozhkovye-kofemashiny', 'price' => 400000,
             'availability' => 'in_stock', 'stock' => 27,
             'image' => '/assets/shop/glow-e2-white-gl-e2-w.png', 'sort' => 100,
             'variant_group' => 'glow-e2', 'color' => 'Белый',
             'summary' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет белый, таймер, подсветка групп, экран настройки температур, PID контроль, система предсмачивания, двойной манометр',
             'description' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет белый, таймер, подсветка групп, экран настройки температур, PID контроль, система предсмачивания, двойной манометр'],
            ['slug' => 'glow-e2-black-white-gl-e2-b-w', 'sku' => 'GL-E2-B&W',
             'brand' => 'Carimali', 'title' => 'GLOW E2 BLACK&WHITE',
             'category' => 'rozhkovye-kofemashiny', 'price' => 400000,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/glow-e2-black-white-gl-e2-b-w.png', 'sort' => 110,
             'variant_group' => 'glow-e2', 'color' => 'Чёрный с белым',
             'summary' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет белый верх + чёрный низ, таймер, подсветка групп, экран настройки температур, PID контроль, система предсмачивания,',
             'description' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет белый верх + чёрный низ, таймер, подсветка групп, экран настройки температур, PID контроль, система предсмачивания, двойной манометр'],
            ['slug' => 'glow-e2-black-wood-gl-e2-b-wd', 'sku' => 'GL-E2-B&WD',
             'brand' => 'Carimali', 'title' => 'GLOW E2 BLACK&WOOD',
             'category' => 'rozhkovye-kofemashiny', 'price' => 400000,
             'availability' => 'in_stock', 'stock' => 24,
             'image' => '/assets/shop/glow-e2-black-wood-gl-e2-b-wd.png', 'sort' => 120,
             'variant_group' => 'glow-e2', 'color' => 'Чёрный с деревом',
             'summary' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет черный + деревянные боковые панели корпуса, таймер6 подсветка групп, экран настройки температур, PID контроль, сист',
             'description' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет черный + деревянные боковые панели корпуса, таймер6 подсветка групп, экран настройки температур, PID контроль, система предсмачивания, двойной манометр'],
            ['slug' => 'glow-e2-grey-gl-e2-g', 'sku' => 'GL-E2-G',
             'brand' => 'Carimali', 'title' => 'GLOW E2 GREY',
             'category' => 'rozhkovye-kofemashiny', 'price' => 400000,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/glow-e2-grey-gl-e2-g.png', 'sort' => 130,
             'variant_group' => 'glow-e2', 'color' => 'Серый',
             'summary' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет серый, таймер, подсветка групп, экран настройки температур, PID контроль, система предсмачивания, двойной манометр',
             'description' => '2 группы, автомат, высокие группы, объем бойлера 11 литров, цвет серый, таймер, подсветка групп, экран настройки температур, PID контроль, система предсмачивания, двойной манометр'],
            ['slug' => 'glow-e2-grey-black-gl-e2-g-b', 'sku' => 'GL-E2-G&B',
             'brand' => 'Carimali', 'title' => 'GLOW E2 GREY&BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 400000,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/glow-e2-grey-black-gl-e2-g-b.png', 'sort' => 140,
             'variant_group' => 'glow-e2', 'color' => 'Серый с чёрным',
             'summary' => 'под заказ',
             'description' => 'под заказ'],
            ['slug' => 'bubble-e1-high-white-bu-e1-h-01-w', 'sku' => 'BU-E1-H-01-W',
             'brand' => 'Carimali', 'title' => 'BUBBLE E1 HIGH WHITE',
             'category' => 'rozhkovye-kofemashiny', 'price' => 383852,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/bubble-e1-high-white-bu-e1-h-01-w.jpg', 'sort' => 150,
             'variant_group' => 'bubble-e1-high', 'color' => 'Белый',
             'summary' => '1 группа, автомат, бойлер 5 литров, высокие группы, цвет белый, экономайзер, таймер, экран настройки температур, PID контроль, система предсмачивания',
             'description' => '1 группа, автомат, бойлер 5 литров, высокие группы, цвет белый, экономайзер, таймер, экран настройки температур, PID контроль, система предсмачивания'],
            ['slug' => 'bubble-e1-high-black-bu-e1-h-01-b', 'sku' => 'BU-E1-H-01-B',
             'brand' => 'Carimali', 'title' => 'BUBBLE E1 HIGH BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 383852,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/bubble-e1-high-black-bu-e1-h-01-b.jpg', 'sort' => 160,
             'variant_group' => 'bubble-e1-high', 'color' => 'Чёрный',
             'summary' => '1 группа, автомат, бойлер 5 литров, высокие группы, цвет чёрный, экономайзер, таймер, экран настройки температур, PID контроль, система предсмачивания',
             'description' => '1 группа, автомат, бойлер 5 литров, высокие группы, цвет чёрный, экономайзер, таймер, экран настройки температур, PID контроль, система предсмачивания'],
            ['slug' => 'bubble-e2-high-white-bu-e2-h-02-w', 'sku' => 'BU-E2-H-02-W',
             'brand' => 'Carimali', 'title' => 'BUBBLE E2 HIGH WHITE',
             'category' => 'rozhkovye-kofemashiny', 'price' => 441949,
             'availability' => 'in_stock', 'stock' => 9,
             'image' => '/assets/shop/bubble-e2-high-white-bu-e2-h-02-w.jpg', 'sort' => 170,
             'variant_group' => 'bubble-e2-high', 'color' => 'Белый',
             'summary' => '2 группы, автомат, бойлер 11 литров, высокие группы, цвет белый, экономайзер, таймер, экран настройки температур, PID контроль, система предсмачивания (в комплекте 3 холдера: 2 дво',
             'description' => '2 группы, автомат, бойлер 11 литров, высокие группы, цвет белый, экономайзер, таймер, экран настройки температур, PID контроль, система предсмачивания (в комплекте 3 холдера: 2 двойных на 18 г и 1 одинарный на 7 г)'],
            ['slug' => 'bubble-e2-high-black-bu-e2-h-02-b', 'sku' => 'BU-E2-H-02-B',
             'brand' => 'Carimali', 'title' => 'BUBBLE E2 HIGH BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 441949,
             'availability' => 'in_stock', 'stock' => 43,
             'image' => '/assets/shop/bubble-e2-high-black-bu-e2-h-02-b.jpg', 'sort' => 180,
             'variant_group' => 'bubble-e2-high', 'color' => 'Чёрный',
             'summary' => '2 группы, автомат, бойлер 11 литров, высокие группы, цвет чёрный, экономайзер, таймер, экран настройки температур, PID контроль, система предсмачивания (в комплекте 3 холдера: 2 дв',
             'description' => '2 группы, автомат, бойлер 11 литров, высокие группы, цвет чёрный, экономайзер, таймер, экран настройки температур, PID контроль, система предсмачивания (в комплекте 3 холдера: 2 двойных на 18 г и 1 одинарный на 7 г)'],
            ['slug' => 'bubble-e3-high-white-bu-e3-h-03-w', 'sku' => 'BU-E3-H-03-W',
             'brand' => 'Carimali', 'title' => 'BUBBLE E3 HIGH WHITE',
             'category' => 'rozhkovye-kofemashiny', 'price' => 569160,
             'availability' => 'in_stock', 'stock' => 5,
             'image' => '/assets/shop/bubble-e3-high-white-bu-e3-h-03-w.jpg', 'sort' => 190,
             'variant_group' => 'bubble-e3-high', 'color' => 'Белый',
             'summary' => '3 группы, автомат, бойлер 14 литров, высокие группы, цвет белый, экономайзер, таймер, экран настройки температур, PID контроль, система предсмачивания (в комплекте 4 холдера: 3 дво',
             'description' => '3 группы, автомат, бойлер 14 литров, высокие группы, цвет белый, экономайзер, таймер, экран настройки температур, PID контроль, система предсмачивания (в комплекте 4 холдера: 3 двойных на 18 г и 1 одинарный на 7 г)'],
            ['slug' => 'bubble-e3-high-black-bu-e3-h-03-b', 'sku' => 'BU-E3-H-03-B',
             'brand' => 'Carimali', 'title' => 'BUBBLE E3 HIGH BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 569160,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/bubble-e3-high-black-bu-e3-h-03-b.jpg', 'sort' => 200,
             'variant_group' => 'bubble-e3-high', 'color' => 'Чёрный',
             'summary' => '3 группы, автомат, бойлер 14 литров, высокие группы, цвет чёрный, экономайзер, таймер, экран настройки температур, PID контроль, система предсмачивания (в комплекте 4 холдера: 3 дв',
             'description' => '3 группы, автомат, бойлер 14 литров, высокие группы, цвет чёрный, экономайзер, таймер, экран настройки температур, PID контроль, система предсмачивания (в комплекте 4 холдера: 3 двойных на 18 г и 1 одинарный на 7 г)'],
            ['slug' => 'divapro-2eh-vysokie-gruppy-div-e2-h-02', 'sku' => 'DIV-E2-H-02',
             'brand' => 'Carimali', 'title' => 'DIVAPRO 2EH ВЫСОКИЕ ГРУППЫ',
             'category' => 'rozhkovye-kofemashiny', 'price' => 864871,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/divapro-2eh-vysokie-gruppy-div-e2-h-02.jpg', 'sort' => 210,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '2 группы, автомат, высокие группы, паровики cool touch, раздельная настройка температуры на группах, бойлер 11,5 л, сенсорный экран, PID контроль, система предсмачивания, автоматич',
             'description' => '2 группы, автомат, высокие группы, паровики cool touch, раздельная настройка температуры на группах, бойлер 11,5 л, сенсорный экран, PID контроль, система предсмачивания, автоматическая чистка, RGB-подсветка зоны приготовления и корпуса'],
            ['slug' => 'divapro-2eh-vysokie-gruppy-avtokapuchinator-div-e2-h-02-lm', 'sku' => 'DIV-E2-H-02-LM',
             'brand' => 'Carimali', 'title' => 'DIVAPRO 2EH ВЫСОКИЕ ГРУППЫ + АВТОКАПУЧИНАТОР',
             'category' => 'rozhkovye-kofemashiny', 'price' => 903981,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/divapro-2eh-vysokie-gruppy-avtokapuchinator-div-e2-h-02-lm.jpg', 'sort' => 220,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '2 группы, автомат, высокие группы, паровики cool touch, раздельная настройка температуры на группах, бойлер 11,5 л, сенсорный экран, PID контроль, система предсмачивания, автоматич',
             'description' => '2 группы, автомат, высокие группы, паровики cool touch, раздельная настройка температуры на группах, бойлер 11,5 л, сенсорный экран, PID контроль, система предсмачивания, автоматическая чистка, автокапучинатор на 1 группу, RGB-подсветка зоны приготовления и корпуса'],
            ['slug' => 'divapro-3eh-vysokie-gruppy-div-e3-h-03', 'sku' => 'DIV-E3-H-03',
             'brand' => 'Carimali', 'title' => 'DIVAPRO 3EH ВЫСОКИЕ ГРУППЫ',
             'category' => 'rozhkovye-kofemashiny', 'price' => 1063770,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/divapro-3eh-vysokie-gruppy-div-e3-h-03.jpg', 'sort' => 230,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '3 группы, автомат, высокие группы, паровики cool touch, раздельная настройка температуры на группах, бойлер 16 л, сенсорный экран, PID контроль, система предсмачивания, автоматичес',
             'description' => '3 группы, автомат, высокие группы, паровики cool touch, раздельная настройка температуры на группах, бойлер 16 л, сенсорный экран, PID контроль, система предсмачивания, автоматическая чистка, RGB-подсветка зоны приготовления и корпуса'],
            ['slug' => 'divapro-3eh-vysokie-gruppy-avtokapuchinator-div-e3-h-03-lm', 'sku' => 'DIV-E3-H-03-LM',
             'brand' => 'Carimali', 'title' => 'DIVAPRO 3EH ВЫСОКИЕ ГРУППЫ + АВТОКАПУЧИНАТОР',
             'category' => 'rozhkovye-kofemashiny', 'price' => 1101761,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/divapro-3eh-vysokie-gruppy-avtokapuchinator-div-e3-h-03-lm.jpg', 'sort' => 240,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '3 группы, автомат, высокие группы, паровики cool touch, раздельная настройка температуры на группах, бойлер 16 л, сенсорный экран, PID контроль, система предсмачивания, автоматичес',
             'description' => '3 группы, автомат, высокие группы, паровики cool touch, раздельная настройка температуры на группах, бойлер 16 л, сенсорный экран, PID контроль, система предсмачивания, автоматическая чистка, автокапучинатор на 1 группу, RGB-подсветка зоны приготовления и корпуса'],
            ['slug' => 'evok-2eh-black-evok-e2-h-b', 'sku' => 'EVOK-E2-H-B',
             'brand' => 'Carimali', 'title' => 'EVOK 2EH BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 924000,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/evok-2eh-black-evok-e2-h-b.png', 'sort' => 250,
             'variant_group' => NULL, 'color' => 'Чёрный',
             'summary' => '2 группы, автомат, высокие группы, цвет чёрный, паровики cool touch, сенсорный дисплей, экономайзер, таймер, PID контроль, улучшенная термоизоляция, бойлер 11 л, автоматическая чис',
             'description' => '2 группы, автомат, высокие группы, цвет чёрный, паровики cool touch, сенсорный дисплей, экономайзер, таймер, PID контроль, улучшенная термоизоляция, бойлер 11 л, автоматическая чистка, RGBподсветка зоны приготовления и корпуса'],
            ['slug' => 'evok-2eh-as-black-evok-e2-h-b-as1', 'sku' => 'EVOK-E2-H-B-AS1',
             'brand' => 'Carimali', 'title' => 'EVOK 2EH AS BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 994035,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/evok-2eh-as-black-evok-e2-h-b-as1.png', 'sort' => 260,
             'variant_group' => NULL, 'color' => 'Чёрный',
             'summary' => '2 группы, автомат, высокие группы, цвет чёрный, паровики cool touch, сенсорный дисплей, экономайзер, таймер, PID контроль, улучшенная термоизоляция, бойлер 11 л, автоматическая чис',
             'description' => '2 группы, автомат, высокие группы, цвет чёрный, паровики cool touch, сенсорный дисплей, экономайзер, таймер, PID контроль, улучшенная термоизоляция, бойлер 11 л, автоматическая чистка, RGBподсветка зоны приготовления и корпуса, автостимер на 2 режима работы – 1 шт.'],
            ['slug' => 'evok-2eh-lm-black-evok-e2-h-b-lm', 'sku' => 'EVOK-E2-H-B-LM',
             'brand' => 'Carimali', 'title' => 'EVOK 2EH LM BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 1005900,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/evok-2eh-lm-black-evok-e2-h-b-lm.png', 'sort' => 270,
             'variant_group' => NULL, 'color' => 'Чёрный',
             'summary' => '2 группы, автомат, высокие группы, цвет чёрный, паровики cool touch, сенсорный дисплей, экономайзер, таймер, PID контроль, улучшенная термоизоляция, бойлер 11 л, автоматическая чис',
             'description' => '2 группы, автомат, высокие группы, цвет чёрный, паровики cool touch, сенсорный дисплей, экономайзер, таймер, PID контроль, улучшенная термоизоляция, бойлер 11 л, автоматическая чистка, RGBподсветка зоны приготовления и корпуса, автокапучинатор с настройкой рецептов молочных напитков – 1 шт.'],
            ['slug' => 'evok-2eh-lm-as-black-evok-e2-h-b-lm-as1', 'sku' => 'EVOK-E2-H-B-LM-AS1',
             'brand' => 'Carimali', 'title' => 'EVOK 2EH LM+AS BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 1075935,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/evok-2eh-lm-as-black-evok-e2-h-b-lm-as1.png', 'sort' => 280,
             'variant_group' => NULL, 'color' => 'Чёрный',
             'summary' => '2 группы, автомат, высокие группы, цвет чёрный, паровики cool touch, сенсорный дисплей, экономайзер, таймер, PID контроль, улучшенная термоизоляция, бойлер 11 л, автоматическая чис',
             'description' => '2 группы, автомат, высокие группы, цвет чёрный, паровики cool touch, сенсорный дисплей, экономайзер, таймер, PID контроль, улучшенная термоизоляция, бойлер 11 л, автоматическая чистка, RGBподсветка зоны приготовления и корпуса, автокапучинатор с настройкой рецептов молочных напитков – 1 шт., автостимер на 2 режима работы – 1 шт.'],
            ['slug' => 'evok-3eh-black-evok-e3-h-b', 'sku' => 'EVOK-E3-H-B',
             'brand' => 'Carimali', 'title' => 'EVOK 3EH BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 1066800,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/evok-3eh-black-evok-e3-h-b.png', 'sort' => 290,
             'variant_group' => NULL, 'color' => 'Чёрный',
             'summary' => '3 группы, автомат, высокие группы, цвет чёрный, паровики cool touch, сенсорный дисплей, экономайзер, таймер, PID контроль, улучшенная термоизоляция, бойлер 11 л, автоматическая чис',
             'description' => '3 группы, автомат, высокие группы, цвет чёрный, паровики cool touch, сенсорный дисплей, экономайзер, таймер, PID контроль, улучшенная термоизоляция, бойлер 11 л, автоматическая чистка, RGBподсветка зоны приготовления и корпуса'],
            ['slug' => 'indie-2gr-inox-black-ind-e2-b', 'sku' => 'IND-E2-B',
             'brand' => 'Carimali', 'title' => 'INDIE 2GR INOX BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 1714702,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/indie-2gr-inox-black-ind-e2-b.png', 'sort' => 300,
             'variant_group' => NULL, 'color' => 'Чёрный',
             'summary' => '2 группы, автомат, высокие группы, цвет чёрный + металлик, паровой бойлер 12 л, бойлеры на группы по 0,6 л (проточные), паровики cool touch, настраиваемые давление и влажность пара',
             'description' => '2 группы, автомат, высокие группы, цвет чёрный + металлик, паровой бойлер 12 л, бойлеры на группы по 0,6 л (проточные), паровики cool touch, настраиваемые давление и влажность пара, экономайзер с настройкой температуры кипятка, раздельная настройка температуры на группы, подсветка рабочей зоны и задней панели'],
            ['slug' => 'indie-2gr-ice-white-ind-e2-w', 'sku' => 'IND-E2-W',
             'brand' => 'Carimali', 'title' => 'INDIE 2GR ICE WHITE',
             'category' => 'rozhkovye-kofemashiny', 'price' => 1714702,
             'availability' => 'in_stock', 'stock' => 2,
             'image' => '/assets/shop/indie-2gr-ice-white-ind-e2-w.png', 'sort' => 310,
             'variant_group' => NULL, 'color' => 'Белый',
             'summary' => '2 группы, автомат, высокие группы, цвет белый + металлик, паровой бойлер 12 л, бойлеры на группы по 0,6 л (проточные), паровики cool touch, настраиваемые давление и влажность пара,',
             'description' => '2 группы, автомат, высокие группы, цвет белый + металлик, паровой бойлер 12 л, бойлеры на группы по 0,6 л (проточные), паровики cool touch, настраиваемые давление и влажность пара, экономайзер с настройкой температуры кипятка, раздельная настройка температуры на группы, подсветка рабочей зоны и задней панели'],
            ['slug' => 'indie-3gr-inox-black-ind-e3-b', 'sku' => 'IND-E3-B',
             'brand' => 'Carimali', 'title' => 'INDIE 3GR INOX BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 2146462,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/indie-3gr-inox-black-ind-e3-b.png', 'sort' => 320,
             'variant_group' => NULL, 'color' => 'Чёрный',
             'summary' => '3 группы, автомат, высокие группы, цвет чёрный + металлик, паровой бойлер 16 л, бойлеры на группы по 0,6 л (проточные), паровики cool touch, настраиваемые давление и влажность пара',
             'description' => '3 группы, автомат, высокие группы, цвет чёрный + металлик, паровой бойлер 16 л, бойлеры на группы по 0,6 л (проточные), паровики cool touch, настраиваемые давление и влажность пара, экономайзер с настройкой температуры кипятка, раздельная настройка температуры на группы, подсветка рабочей зоны и задней панели'],
            ['slug' => 'indie-3gr-ice-white-ind-e3-w', 'sku' => 'IND-E3-W',
             'brand' => 'Carimali', 'title' => 'INDIE 3GR ICE WHITE',
             'category' => 'rozhkovye-kofemashiny', 'price' => 2146462,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/indie-3gr-ice-white-ind-e3-w.png', 'sort' => 330,
             'variant_group' => NULL, 'color' => 'Белый',
             'summary' => '3 группы, автомат, высокие группы, цвет белый + металлик, паровой бойлер 16 л, бойлеры на группы по 0,6 л (проточные), паровики cool touch, настраиваемые давление и влажность пара,',
             'description' => '3 группы, автомат, высокие группы, цвет белый + металлик, паровой бойлер 16 л, бойлеры на группы по 0,6 л (проточные), паровики cool touch, настраиваемые давление и влажность пара, экономайзер с настройкой температуры кипятка, раздельная настройка температуры на группы, подсветка рабочей зоны и задней панели'],
            ['slug' => 'belle-epoque-2gr-copper-brass-be-2-c-b', 'sku' => 'BE-2-C/B',
             'brand' => 'Elektra', 'title' => 'BELLE EPOQUE 2GR Copper/Brass',
             'category' => 'rozhkovye-kofemashiny', 'price' => 1785000,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/belle-epoque-2gr-copper-brass-be-2-c-b.png', 'sort' => 340,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '2 группы, вертикальная, автомат, корпус медь/латунь',
             'description' => '2 группы, вертикальная, автомат, корпус медь/латунь'],
            ['slug' => 'belle-epoque-2gr-chrome-be-2-lc', 'sku' => 'BE-2-LC',
             'brand' => 'Elektra', 'title' => 'BELLE EPOQUE 2GR Chrome',
             'category' => 'rozhkovye-kofemashiny', 'price' => 1787698,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/belle-epoque-2gr-chrome-be-2-lc.png', 'sort' => 350,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '2 группы, вертикальная, автомат, корпус хромированный',
             'description' => '2 группы, вертикальная, автомат, корпус хромированный'],
            ['slug' => 'belle-epoque-2gr-riforma-be-2-ri', 'sku' => 'BE-2-RI',
             'brand' => 'Elektra', 'title' => 'BELLE EPOQUE 2GR Riforma',
             'category' => 'rozhkovye-kofemashiny', 'price' => 1834920,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/belle-epoque-2gr-riforma-be-2-ri.png', 'sort' => 360,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '2 группы, вертикальная, автомат, Riforma Limited Edition, корпус медь/окисленная латунь',
             'description' => '2 группы, вертикальная, автомат, Riforma Limited Edition, корпус медь/окисленная латунь'],
            ['slug' => 'belle-epoque-3gr-copper-brass-be-3-c-b', 'sku' => 'BE-3-C/B',
             'brand' => 'Elektra', 'title' => 'BELLE EPOQUE 3GR Copper/Brass',
             'category' => 'rozhkovye-kofemashiny', 'price' => 2083174,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/belle-epoque-3gr-copper-brass-be-3-c-b.png', 'sort' => 370,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '3 группы, вертикальная, автомат, корпус медь/латунь',
             'description' => '3 группы, вертикальная, автомат, корпус медь/латунь'],
            ['slug' => 'belle-epoque-3gr-chrome-be-3-lc', 'sku' => 'BE-3-LC',
             'brand' => 'Elektra', 'title' => 'BELLE EPOQUE 3GR Chrome',
             'category' => 'rozhkovye-kofemashiny', 'price' => 2010317,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/belle-epoque-3gr-chrome-be-3-lc.png', 'sort' => 380,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '3 группы, вертикальная, автомат, корпус хромированный',
             'description' => '3 группы, вертикальная, автомат, корпус хромированный'],
            ['slug' => 'belle-epoque-3gr-riforma-be-3-ri', 'sku' => 'BE-3-RI',
             'brand' => 'Elektra', 'title' => 'BELLE EPOQUE 3GR Riforma',
             'category' => 'rozhkovye-kofemashiny', 'price' => 2077777,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/belle-epoque-3gr-riforma-be-3-ri.png', 'sort' => 390,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '3 группы, вертикальная, автомат, Riforma Limited Edition, корпус медь/окисленная латунь',
             'description' => '3 группы, вертикальная, автомат, Riforma Limited Edition, корпус медь/окисленная латунь'],
            ['slug' => 'heylo-coffee-black-26302-2839hey-cof-blckhey-cof-wht', 'sku' => '26302-2839HEY-COF-BLCKHEY-COF-WHT',
             'brand' => 'Heylo', 'title' => 'HEYLO COFFEE BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 772117,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/heylo-coffee-black-26302-2839hey-cof-blckhey-cof-wht.png', 'sort' => 400,
             'variant_group' => NULL, 'color' => 'Чёрный',
             'summary' => 'Безбойлерный кофейный модуль HEYLO на 1 группу, индукционная технология, профилирование температуры и давления, цвет чёрный/графит',
             'description' => 'Безбойлерный кофейный модуль HEYLO на 1 группу, индукционная технология, профилирование температуры и давления, цвет чёрный/графит'],
            ['slug' => 'heylo-milk-black-7091723766hey-milk-blckhey-milk-wht', 'sku' => '7091723766HEY-MILK-BLCKHEY-MILK-WHT',
             'brand' => 'Heylo', 'title' => 'HEYLO MILK BLACK',
             'category' => 'rozhkovye-kofemashiny', 'price' => 772117,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/heylo-milk-black-7091723766hey-milk-blckhey-milk-wht.png', 'sort' => 410,
             'variant_group' => NULL, 'color' => 'Чёрный',
             'summary' => 'Безбойлерный молочный модуль HEYLO , индукционная технология нагрева, технология вспенивания молока без пара, приготовление холодной молочной пены, цвет чёрный/графит',
             'description' => 'Безбойлерный молочный модуль HEYLO , индукционная технология нагрева, технология вспенивания молока без пара, приготовление холодной молочной пены, цвет чёрный/графит'],
            ['slug' => 'heylo-steam-hey-steam', 'sku' => 'HEY-STEAM',
             'brand' => 'Heylo', 'title' => 'HEYLO STEAM',
             'category' => 'rozhkovye-kofemashiny', 'price' => 463270,
             'availability' => 'in_stock', 'stock' => 1,
             'image' => '/assets/shop/heylo-steam-hey-steam.png', 'sort' => 420,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Паровой модуль HEYLO ,цвет черный/графит',
             'description' => 'Паровой модуль HEYLO ,цвет черный/графит'],
            ['slug' => 'mya-ultra-mu-01-01-00', 'sku' => 'MU-01-01-00',
             'brand' => 'Carimali', 'title' => 'MYA ULTRA',
             'category' => 'superavtomaty', 'price' => 602251,
             'availability' => 'in_stock', 'stock' => 12,
             'image' => '/assets/shop/mya-ultra-mu-01-01-00.jpg', 'sort' => 430,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Свежее молоко + 1 бункер для зерна + работа от водопровода, ЦУ M-Brew XL на 10-20 г молотого кофе, молочная помпа CARImilk Static, трубка пара бариста (авто-стимер) touch-screen 10',
             'description' => 'Свежее молоко + 1 бункер для зерна + работа от водопровода, ЦУ M-Brew XL на 10-20 г молотого кофе, молочная помпа CARImilk Static, трубка пара бариста (авто-стимер) touch-screen 10", производительность 400 чашек'],
            ['slug' => 'armonia-light-e-1m-2g-1s-1x-wm-al-01-02-01', 'sku' => 'AL-01-02-01',
             'brand' => 'Carimali', 'title' => 'ARMONIA LIGHT E 1M 2G 1S 1X WM',
             'category' => 'superavtomaty', 'price' => 719250,
             'availability' => 'in_stock', 'stock' => 14,
             'image' => NULL, 'sort' => 440,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Свежее молоко + 2 бункера для зерна + 1 бункера для порошков, работа от водопровода, ЦУ M-Brew L на 8-16 г молотого кофе, молочная помпа, touchscreen 10", производительность 150 ча',
             'description' => 'Свежее молоко + 2 бункера для зерна + 1 бункера для порошков, работа от водопровода, ЦУ M-Brew L на 8-16 г молотого кофе, молочная помпа, touchscreen 10", производительность 150 чашек'],
            ['slug' => 'armonia-light-e-1m-1g-2s-2x-wm-al-01-01-02', 'sku' => 'AL-01-01-02',
             'brand' => 'Carimali', 'title' => 'ARMONIA LIGHT E 1M 1G 2S 2X WM',
             'category' => 'superavtomaty', 'price' => 719250,
             'availability' => 'in_stock', 'stock' => 3,
             'image' => '/assets/shop/armonia-light-e-1m-1g-2s-2x-wm-al-01-01-02.png', 'sort' => 450,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Свежее молоко + 1 бункер для зерна + 2 бункера для порошков, работа от водопровода, ЦУ M-Brew L на 8-16 г молотого кофе, молочная помпа, touchscreen 10", производительность 150 чаш',
             'description' => 'Свежее молоко + 1 бункер для зерна + 2 бункера для порошков, работа от водопровода, ЦУ M-Brew L на 8-16 г молотого кофе, молочная помпа, touchscreen 10", производительность 150 чашек'],
            ['slug' => 'silverace-e-1m-2g-2s-2x-wm-sa-01-02-02', 'sku' => 'SA-01-02-02',
             'brand' => 'Carimali', 'title' => 'SILVERACE E 1M 2G 2S 2X WM',
             'category' => 'superavtomaty', 'price' => 1044843,
             'availability' => 'in_stock', 'stock' => 5,
             'image' => NULL, 'sort' => 460,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Свежее молоко + 2 бункера для зерна + 2 бункера для порошков, работа от водопровода, ЦУ M-Brew L на 8-16 г молотого кофе, молочная помпа, touchscreen 10", WiFi-модуль, MDBподключен',
             'description' => 'Свежее молоко + 2 бункера для зерна + 2 бункера для порошков, работа от водопровода, ЦУ M-Brew L на 8-16 г молотого кофе, молочная помпа, touchscreen 10", WiFi-модуль, MDBподключение, производительность 250 чашек'],
            ['slug' => 'silverace-e-1m-1g-2s-2x-wm-sa-01-01-02', 'sku' => 'SA-01-01-02',
             'brand' => 'Carimali', 'title' => 'SILVERACE E 1M 1G 2S 2X WM',
             'category' => 'superavtomaty', 'price' => 992722,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/silverace-e-1m-1g-2s-2x-wm-sa-01-01-02.jpg', 'sort' => 470,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Свежее молоко + 1 бункер для зерна + 2 бункера для порошков, работа от водопровода, ЦУ M-Brew L на 8-16 г молотого кофе, молочная помпа, touchscreen 10", , WiFi-модуль, MDBподключе',
             'description' => 'Свежее молоко + 1 бункер для зерна + 2 бункера для порошков, работа от водопровода, ЦУ M-Brew L на 8-16 г молотого кофе, молочная помпа, touchscreen 10", , WiFi-модуль, MDBподключение, производительность 250 чашек'],
            ['slug' => 'blue-26-e-0m-1g-2s-1x-wj-bd-26-00-01-02', 'sku' => 'BD-26-00-01-02',
             'brand' => 'Carimali', 'title' => 'BLUE 26 E 0M 1G 2S 1X WJ',
             'category' => 'superavtomaty', 'price' => 419444,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 480,
             'variant_group' => NULL, 'color' => 'Синий',
             'summary' => '1 бункер для зерна + 2 для порошков + работа от водопровода, аналоговый дисплей, производительность 85 чашек',
             'description' => '1 бункер для зерна + 2 для порошков + работа от водопровода, аналоговый дисплей, производительность 85 чашек'],
            ['slug' => 'blue-26-e-1m-1g-0s-0x-wm-bd26-01-01-00', 'sku' => 'BD26-01-01-00',
             'brand' => 'Carimali', 'title' => 'BLUE 26 E 1M 1G 0S 0X WM',
             'category' => 'rozhkovye-kofemashiny', 'price' => 437852,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 490,
             'variant_group' => NULL, 'color' => 'Синий',
             'summary' => 'Свежее молоко + 1 бункер для зерна + работа от водопровода, аналоговый дисплей, производительность 85 чашек',
             'description' => 'Свежее молоко + 1 бункер для зерна + работа от водопровода, аналоговый дисплей, производительность 85 чашек'],
            ['slug' => 'blue-26-e-1m-2g-0s-0x-wm-bd26-01-02-00', 'sku' => 'BD26-01-02-00',
             'brand' => 'Carimali', 'title' => 'BLUE 26 E 1M 2G 0S 0X WM',
             'category' => 'rozhkovye-kofemashiny', 'price' => 475983,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/blue-26-e-1m-2g-0s-0x-wm-bd26-01-02-00.jpg', 'sort' => 500,
             'variant_group' => NULL, 'color' => 'Синий',
             'summary' => 'Свежее молоко + 2 бункера для зерна + работа от водопровода, аналоговый дисплей, производительность 85 чашек',
             'description' => 'Свежее молоко + 2 бункера для зерна + работа от водопровода, аналоговый дисплей, производительность 85 чашек'],
            ['slug' => 'blue-26-plus-e-0m-1g-2s-1x-wj-bd26pl-00-01-02', 'sku' => 'BD26PL-00-01-02',
             'brand' => 'Carimali', 'title' => 'BLUE 26 PLUS E 0M 1G 2S 1X WJ',
             'category' => 'rozhkovye-kofemashiny', 'price' => 486502,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 510,
             'variant_group' => NULL, 'color' => 'Синий',
             'summary' => '1 бункер для зерна + 2 для порошков + работа от водопровода, touch screen 7", производительность 85 чашек',
             'description' => '1 бункер для зерна + 2 для порошков + работа от водопровода, touch screen 7", производительность 85 чашек'],
            ['slug' => 'blue-26-plus-e-1m-1g-0s-0x-wm-bd26pl-01-01-00', 'sku' => 'BD26PL-01-01-00',
             'brand' => 'Carimali', 'title' => 'BLUE 26 PLUS E 1M 1G 0S 0X WM',
             'category' => 'rozhkovye-kofemashiny', 'price' => 515430,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 520,
             'variant_group' => NULL, 'color' => 'Синий',
             'summary' => 'Свежее молоко + 1 бункер для зерна + работа от водопровода, touch screen 7", производительность 85 чашек',
             'description' => 'Свежее молоко + 1 бункер для зерна + работа от водопровода, touch screen 7", производительность 85 чашек'],
            ['slug' => 'blue-26-plus-e-1m-2g-0s-0x-wm-bd26pl-01-02-00', 'sku' => 'BD26PL-01-02-00',
             'brand' => 'Carimali', 'title' => 'BLUE 26 PLUS E 1M 2G 0S 0X WM',
             'category' => 'rozhkovye-kofemashiny', 'price' => 553561,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/blue-26-plus-e-1m-2g-0s-0x-wm-bd26pl-01-02-00.jpg', 'sort' => 530,
             'variant_group' => NULL, 'color' => 'Синий',
             'summary' => 'Свежее молоко + 2 бункера для зерна + работа от водопровода, touch screen 7", производительность 85 чашек',
             'description' => 'Свежее молоко + 2 бункера для зерна + работа от водопровода, touch screen 7", производительность 85 чашек'],
            ['slug' => 'bluedot-e-0m-1g-3s-2x-nw-bd-00-01-03-nw', 'sku' => 'BD-00-01-03-NW',
             'brand' => 'Carimali', 'title' => 'BLUEDOT E 0M 1G 3S 2X NW',
             'category' => 'superavtomaty', 'price' => 262500,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/bluedot-e-0m-1g-3s-2x-nw-bd-00-01-03-nw.jpg', 'sort' => 540,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '1 бункер для зерна + 3 для порошков работа только от водопровода, цвет чёрный, бункер для отходов, без крана для кипятка, без внутреннего бака для воды,увеличенный бункер для зерна',
             'description' => '1 бункер для зерна + 3 для порошков работа только от водопровода, цвет чёрный, бункер для отходов, без крана для кипятка, без внутреннего бака для воды,увеличенный бункер для зерна 1,8 кг, увеличенный бункер для порошков 0,8 кг (2 шт.), увеличенный бункер для порошков 1,8 кг (1 шт.), производительность 100 чашек'],
            ['slug' => 'bluedot-e-0m-1g-3s-2x-wm-bd-00-01-03', 'sku' => 'BD-00-01-03',
             'brand' => 'Carimali', 'title' => 'BLUEDOT E 0M 1G 3S 2X WM',
             'category' => 'superavtomaty', 'price' => 499651,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 550,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '1 бункер для зерна + 3 бункера для порошков + работа от бака или водопровода, аналоговый дисплей, производительность 100 чашек',
             'description' => '1 бункер для зерна + 3 бункера для порошков + работа от бака или водопровода, аналоговый дисплей, производительность 100 чашек'],
            ['slug' => 'bluedot-e-0m-2g-2s-2x-wm-bd-00-02-02', 'sku' => 'BD-00-02-02',
             'brand' => 'Carimali', 'title' => 'BLUEDOT E 0M 2G 2S 2X WM',
             'category' => 'superavtomaty', 'price' => 515430,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 560,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '2 бункера для зерна + 2 бункера для порошков + работа от бака или водопровода, аналоговый дисплей, производительность 100 чашек',
             'description' => '2 бункера для зерна + 2 бункера для порошков + работа от бака или водопровода, аналоговый дисплей, производительность 100 чашек'],
            ['slug' => 'bluedot-e-1m-1g-3s-2x-bd-01-01-03', 'sku' => 'BD-01-01-03',
             'brand' => 'Carimali', 'title' => 'BLUEDOT E 1M 1G 3S 2X',
             'category' => 'superavtomaty', 'price' => 599582,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 570,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'под заказ',
             'description' => 'под заказ'],
            ['slug' => 'bluedot-e-1m-2g-2s-2x-bd-01-02-02', 'sku' => 'BD-01-02-02',
             'brand' => 'Carimali', 'title' => 'BLUEDOT E 1M 2G 2S 2X',
             'category' => 'superavtomaty', 'price' => 629824,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/bluedot-e-1m-2g-2s-2x-bd-01-02-02.jpg', 'sort' => 580,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'под заказ',
             'description' => 'под заказ'],
            ['slug' => 'bluedot-plus-e-0m-2g-2s-2x-wj-bdpl-00-02-02', 'sku' => 'BDPL-00-02-02',
             'brand' => 'Carimali', 'title' => 'BLUEDOT PLUS E 0M 2G 2S 2X WJ',
             'category' => 'superavtomaty', 'price' => 604841,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 590,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '2 бункера для зерна + 2 для порошков + работа от бака или водопровода, touch screen 7", производительность 100 чашек',
             'description' => '2 бункера для зерна + 2 для порошков + работа от бака или водопровода, touch screen 7", производительность 100 чашек'],
            ['slug' => 'bluedot-plus-e-0m-1g-3s-2x-wj-bdpl-00-01-03-nw', 'sku' => 'BDPL-00-01-03-NW',
             'brand' => 'Carimali', 'title' => 'BLUEDOT PLUS E 0M 1G 3S 2X WJ',
             'category' => 'superavtomaty', 'price' => 587748,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 600,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '1 бункер для зерна + 3 бункера для порошков + работа от водопровода + бункер для отходов, без крана для кипятка, без внутреннего бака для воды, touch screen 7", производительность ',
             'description' => '1 бункер для зерна + 3 бункера для порошков + работа от водопровода + бункер для отходов, без крана для кипятка, без внутреннего бака для воды, touch screen 7", производительность 100 чашек'],
            ['slug' => 'bluedot-plus-e-1m-1g-3s-2x-wj-bdpl-01-01-03', 'sku' => 'BDPL-01-01-03',
             'brand' => 'Carimali', 'title' => 'BLUEDOT PLUS E 1M 1G 3S 2X WJ',
             'category' => 'superavtomaty', 'price' => 691623,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/bluedot-plus-e-1m-1g-3s-2x-wj-bdpl-01-01-03.jpg', 'sort' => 610,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Свежее молоко + 1 бункер для зерна + 3 для порошков+ работа от бака или водопровода, touch screen 7", производительность 100 чашек',
             'description' => 'Свежее молоко + 1 бункер для зерна + 3 для порошков+ работа от бака или водопровода, touch screen 7", производительность 100 чашек'],
            ['slug' => 'bluedot-plus-e-1m-2g-2s-2x-wj-bdpl-01-02-02', 'sku' => 'BDPL-01-02-02',
             'brand' => 'Carimali', 'title' => 'BLUEDOT PLUS E 1M 2G 2S 2X WJ',
             'category' => 'superavtomaty', 'price' => 715290,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 620,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Свежее молоко + 2 бункера для зерна + 2 для порошков+ работа от бака или водопровода, touch screen 7", производительность 100 чашек',
             'description' => 'Свежее молоко + 2 бункера для зерна + 2 для порошков+ работа от бака или водопровода, touch screen 7", производительность 100 чашек'],
            ['slug' => 'bluedot-power-e-1m-bdpw-01-01-03', 'sku' => 'BDPW-01-01-03',
             'brand' => 'Carimali', 'title' => 'BLUEDOT POWER E 1M',
             'category' => 'superavtomaty', 'price' => 732384,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 630,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'под заказ',
             'description' => 'под заказ'],
            ['slug' => 'bluedot-power-e-1m-bdpw-01-02-02', 'sku' => 'BDPW-01-02-02',
             'brand' => 'Carimali', 'title' => 'BLUEDOT POWER E 1M',
             'category' => 'superavtomaty', 'price' => 756051,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/bluedot-power-e-1m-bdpw-01-02-02.jpg', 'sort' => 640,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'под заказ',
             'description' => 'под заказ'],
            ['slug' => 'armonia-soft-e-0m-1g-2s-2x-wm-as-00-01-02', 'sku' => 'AS-00-01-02',
             'brand' => 'Carimali', 'title' => 'ARMONIA SOFT E 0M 1G 2S 2X WM',
             'category' => 'superavtomaty', 'price' => 733699,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 650,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '1 бункер для зерна + 2 бункера для порошков, работа от водопровода, ЦУ M-Brew L на 8-16 г молотого кофе, аналоговый дисплей, производительность 250 чашек',
             'description' => '1 бункер для зерна + 2 бункера для порошков, работа от водопровода, ЦУ M-Brew L на 8-16 г молотого кофе, аналоговый дисплей, производительность 250 чашек'],
            ['slug' => 'armonia-soft-e-1mcs-as-01-02-01', 'sku' => 'AS-01-02-01',
             'brand' => 'Carimali', 'title' => 'ARMONIA SOFT E 1MCS',
             'category' => 'superavtomaty', 'price' => 894113,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 660,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'под заказ',
             'description' => 'под заказ'],
            ['slug' => 'armonia-ultra-e-0m-1g-2s-2x-wm-au-00-01-02', 'sku' => 'AU-00-01-02',
             'brand' => 'Carimali', 'title' => 'ARMONIA ULTRA E 0M 1G 2S 2X WM',
             'category' => 'superavtomaty', 'price' => 919096,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 670,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '1 бункер для зерна + 2 бункера для порошков, работа от водопровода, ЦУ MBrew L на 8-16 г молотого кофе, touchscreen 10", WiFi-модуль, MDBподключение, производительность 250 чашек',
             'description' => '1 бункер для зерна + 2 бункера для порошков, работа от водопровода, ЦУ MBrew L на 8-16 г молотого кофе, touchscreen 10", WiFi-модуль, MDBподключение, производительность 250 чашек'],
            ['slug' => 'armonia-ultra-e-1mcs-1g-2s-2x-wm-au-01-01-02', 'sku' => 'AU-01-01-02',
             'brand' => 'Carimali', 'title' => 'ARMONIA ULTRA E 1MCS 1G 2S 2X WM',
             'category' => 'superavtomaty', 'price' => 1107122,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 680,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Свежее молоко + 1 бункер для зерна + 2 бункера для порошков, работа от водопровода, ЦУ M-Brew L на 8-16 г молотого кофе, молочная помпа, touchscreen 10", WiFi-модуль, MDBподключени',
             'description' => 'Свежее молоко + 1 бункер для зерна + 2 бункера для порошков, работа от водопровода, ЦУ M-Brew L на 8-16 г молотого кофе, молочная помпа, touchscreen 10", WiFi-модуль, MDBподключение, производительность 250 чашек'],
            ['slug' => 'armonia-ultra-e-1mcs-2g-1s-1x-wm-au-01-02-01', 'sku' => 'AU-01-02-01',
             'brand' => 'Carimali', 'title' => 'ARMONIA ULTRA E 1MCS 2G 1S 1X WM',
             'category' => 'superavtomaty', 'price' => 1109752,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/armonia-ultra-e-1mcs-2g-1s-1x-wm-au-01-02-01.jpg', 'sort' => 690,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Свежее молоко + 2 бункера для зерна + 1 бункер для порошков, работа от водопровода, ЦУ M-Brew L на 8-16 г молотого кофе, молочная помпа, touchscreen 10", WiFi-модуль, MDBподключени',
             'description' => 'Свежее молоко + 2 бункера для зерна + 1 бункер для порошков, работа от водопровода, ЦУ M-Brew L на 8-16 г молотого кофе, молочная помпа, touchscreen 10", WiFi-модуль, MDBподключение, производительность 250 чашек'],
            ['slug' => 'silvertwin-e-0m-1g-3s-st-00-01-03', 'sku' => 'ST-00-01-03',
             'brand' => 'Carimali', 'title' => 'SILVERTWIN E 0M 1G 3S',
             'category' => 'superavtomaty', 'price' => 845468,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 700,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'под заказ',
             'description' => 'под заказ'],
            ['slug' => 'silvertwin-e-1m-2g-1s-st-01-02-01', 'sku' => 'ST-01-02-01',
             'brand' => 'Carimali', 'title' => 'SILVERTWIN E 1M 2G 1S',
             'category' => 'superavtomaty', 'price' => 978658,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/silvertwin-e-1m-2g-1s-st-01-02-01.jpg', 'sort' => 710,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'под заказ',
             'description' => 'под заказ'],
            ['slug' => 'silvertwin-e-1m-2g-2s-st-01-02-02', 'sku' => 'ST-01-02-02',
             'brand' => 'Carimali', 'title' => 'SILVERTWIN E 1M 2G 2S',
             'category' => 'superavtomaty', 'price' => 1001822,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 720,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'под заказ',
             'description' => 'под заказ'],
            ['slug' => 'optima-soft-e-1mcs-1g-wm-os-01-01-00', 'sku' => 'OS-01-01-00',
             'brand' => 'Carimali', 'title' => 'OPTIMA SOFT E 1MCS 1G WM',
             'category' => 'superavtomaty', 'price' => 1044009,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => NULL, 'sort' => 730,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Свеж. Молоко + 1 бункер для зерна, работа от водопровода, молочная помпа CARImilk Static, ЦУ на 8-16 г молотого кофе, аналоговый дисплей, производительность 400 чашек',
             'description' => 'Свеж. Молоко + 1 бункер для зерна, работа от водопровода, молочная помпа CARImilk Static, ЦУ на 8-16 г молотого кофе, аналоговый дисплей, производительность 400 чашек'],
            ['slug' => 'optima-soft-e-1mcs-2g-wm-os-01-02-00', 'sku' => 'OS-01-02-00',
             'brand' => 'Carimali', 'title' => 'OPTIMA SOFT E 1MCS 2G WM',
             'category' => 'superavtomaty', 'price' => 1108437,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/optima-soft-e-1mcs-2g-wm-os-01-02-00.jpg', 'sort' => 740,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Свеж. Молоко + 2 бункера для зерна, работа от водопровода, молочная помпа CARImilk Static, ЦУ на 8-16 г молотого кофе, аналоговый дисплей, производительность 400 чашек',
             'description' => 'Свеж. Молоко + 2 бункера для зерна, работа от водопровода, молочная помпа CARImilk Static, ЦУ на 8-16 г молотого кофе, аналоговый дисплей, производительность 400 чашек'],
            ['slug' => 'x010-od-white-x010-od-w', 'sku' => 'X010_OD_W',
             'brand' => 'Carimali', 'title' => 'X010-OD WHITE',
             'category' => 'kofemolki', 'price' => 73000,
             'availability' => 'in_stock', 'stock' => 20,
             'image' => '/assets/shop/x010-od-white-x010-od-w.png', 'sort' => 750,
             'variant_group' => 'x010-od', 'color' => 'Белый',
             'summary' => '64-мм плоские стальные жернова, бункер 1,7 кг, цвет белый, светодиодная подсветка, Touch-screen с отображением температуры жерновов, влажности, счетчика порций. Прямой помол, 3 нас',
             'description' => '64-мм плоские стальные жернова, бункер 1,7 кг, цвет белый, светодиодная подсветка, Touch-screen с отображением температуры жерновов, влажности, счетчика порций. Прямой помол, 3 настраиваемых дозы (шаг 0,1 сек.): одинарная, двойная + свободный помол. Шаговая настройка помола. Производительность: 16-25 кг/ч'],
            ['slug' => 'x010-od-black-x010-od-b', 'sku' => 'X010_OD_B',
             'brand' => 'Carimali', 'title' => 'X010-OD BLACK',
             'category' => 'kofemolki', 'price' => 73000,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/x010-od-black-x010-od-b.png', 'sort' => 760,
             'variant_group' => 'x010-od', 'color' => 'Чёрный',
             'summary' => '64-мм плоские стальные жернова, бункер 1,7 кг, цвет черный, светодиодная подсветка, Touch-screen с отображением температуры жерновов, влажности, счетчика порций. Прямой помол, 3 на',
             'description' => '64-мм плоские стальные жернова, бункер 1,7 кг, цвет черный, светодиодная подсветка, Touch-screen с отображением температуры жерновов, влажности, счетчика порций. Прямой помол, 3 настраиваемых дозы (шаг 0,1 сек.): одинарная, двойная + свободный помол. Шаговая настройка помола. Производительность: 16-25 кг/ч'],
            ['slug' => 'x010-maxi-white-x010-maxi-w', 'sku' => 'X010_MAXI_W',
             'brand' => 'Carimali', 'title' => 'X010 MAXI WHITE',
             'category' => 'kofemolki', 'price' => 127000,
             'availability' => 'in_stock', 'stock' => 35,
             'image' => '/assets/shop/x010-maxi-white-x010-maxi-w.png', 'sort' => 770,
             'variant_group' => 'x010-maxi', 'color' => 'Белый',
             'summary' => '83-мм плоские стальные жернова, бункер 1,7 кг, цвет белый, светодиодная подсветка, Touch-screen с отображением температуры жерновов, влажности, счетчика порций. Прямой помол, 3 нас',
             'description' => '83-мм плоские стальные жернова, бункер 1,7 кг, цвет белый, светодиодная подсветка, Touch-screen с отображением температуры жерновов, влажности, счетчика порций. Прямой помол, 3 настраиваемых дозы (шаг 0,1 сек.): одинарная, двойная + свободный помол. Шаговая настройка помола. Производительность: 16-25 кг/ч'],
            ['slug' => 'x010-maxi-black-x010-maxi-b', 'sku' => 'X010_MAXI_B',
             'brand' => 'Carimali', 'title' => 'X010 MAXI BLACK',
             'category' => 'kofemolki', 'price' => 127000,
             'availability' => 'in_stock', 'stock' => 72,
             'image' => '/assets/shop/x010-maxi-black-x010-maxi-b.png', 'sort' => 780,
             'variant_group' => 'x010-maxi', 'color' => 'Чёрный',
             'summary' => '83-мм плоские стальные жернова, бункер 1,7 кг, цвет черный, светодиодная подсветка, Touch-screen с отображением температуры жерновов, влажности, счетчика порций. Прямой помол, 3 на',
             'description' => '83-мм плоские стальные жернова, бункер 1,7 кг, цвет черный, светодиодная подсветка, Touch-screen с отображением температуры жерновов, влажности, счетчика порций. Прямой помол, 3 настраиваемых дозы (шаг 0,1 сек.): одинарная, двойная + свободный помол. Шаговая настройка помола. Производительность: 16-25 кг/ч'],
            ['slug' => 'slingshot-talis-s75-slingshot-talis-s75', 'sku' => 'Slingshot Talis S75',
             'brand' => 'Carimali', 'title' => 'Slingshot Talis S75',
             'category' => 'kofemolki', 'price' => 172308,
             'availability' => 'in_stock', 'stock' => 6,
             'image' => '/assets/shop/slingshot-talis-s75-slingshot-talis-s75.jpg', 'sort' => 790,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '75-мм плоские стальные жернова, бункер 1,2 кг, цвет чёрный, светодиодная подсветка, регулируемый кофевод, микрометрическая настройка помола, 3 настраиваемых дозы (шаг 0,05 сек.): о',
             'description' => '75-мм плоские стальные жернова, бункер 1,2 кг, цвет чёрный, светодиодная подсветка, регулируемый кофевод, микрометрическая настройка помола, 3 настраиваемых дозы (шаг 0,05 сек.): одинарная, двойная + свободный помол, датчик срока службы жерновов.'],
            ['slug' => 'slingshot-talis-s75-pro-slingshot-talis-s75-pro', 'sku' => 'Slingshot Talis S75 Pro',
             'brand' => 'Carimali', 'title' => 'Slingshot Talis S75 Pro',
             'category' => 'kofemolki', 'price' => 178690,
             'availability' => 'in_stock', 'stock' => 3,
             'image' => '/assets/shop/slingshot-talis-s75-pro-slingshot-talis-s75-pro.jpg', 'sort' => 800,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => '75-мм плоские титановые жернова, бункер 2 кг с технологией стабилизации давления зерна на жернова Zero Gravity, цвет чёрный, светодиодная подсветка, регулируемый кофевод, микрометр',
             'description' => '75-мм плоские титановые жернова, бункер 2 кг с технологией стабилизации давления зерна на жернова Zero Gravity, цвет чёрный, светодиодная подсветка, регулируемый кофевод, микрометрическая настройка помола, 3 настраиваемых дозы (шаг 0,05 сек.): одинарная, двойная + свободный помол, датчик срока службы жерновов.'],
            ['slug' => 'holodilnik-sc08-sc08', 'sku' => 'SC08',
             'brand' => 'Carimali', 'title' => 'ХОЛОДИЛЬНИК SC08',
             'category' => 'aksessuary', 'price' => 60165,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/holodilnik-sc08-sc08.jpg', 'sort' => 810,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Глухая дверь, камера 8 литров Цвет черный Размеры (ШхВхГ) 240х472х470 Объем холодильной камеры 8 литров Напряжение 220-240 В | 50 Гц, мощность 65 Вт Автоматическая разморозка для о',
             'description' => 'Глухая дверь, камера 8 литров Цвет черный Размеры (ШхВхГ) 240х472х470 Объем холодильной камеры 8 литров Напряжение 220-240 В | 50 Гц, мощность 65 Вт Автоматическая разморозка для обеспечения эффективности охлаждения'],
            ['slug' => 'holodilnik-fridge-c-dgt-fridge-c-dgt', 'sku' => 'FRIDGE-C DGT',
             'brand' => 'Carimali', 'title' => 'ХОЛОДИЛЬНИК FRIDGE-C DGT',
             'category' => 'aksessuary', 'price' => 48693,
             'availability' => 'in_stock', 'stock' => 39,
             'image' => '/assets/shop/holodilnik-fridge-c-dgt-fridge-c-dgt.jpg', 'sort' => 820,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Прозрачная дверца и электронный контроль температуры, цвет черныйРазмеры (ШхВхГ) 220x456x516 ммМасса 16 кгОбъем холодильной камеры 7 лОбъем контейнера для молока 4,5 л Напряжение 2',
             'description' => 'Прозрачная дверца и электронный контроль температуры, цвет черныйРазмеры (ШхВхГ) 220x456x516 ммМасса 16 кгОбъем холодильной камеры 7 лОбъем контейнера для молока 4,5 л Напряжение 220-240 В 50/60 Гц, мощность 120 Вт'],
            ['slug' => 'cup-warmer-plus-cup-warmer-plus', 'sku' => 'CUP WARMER PLUS',
             'brand' => 'Carimali', 'title' => 'CUP WARMER PLUS',
             'category' => 'superavtomaty', 'price' => 138384,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/cup-warmer-plus-cup-warmer-plus.jpg', 'sort' => 830,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'под заказ',
             'description' => 'под заказ'],
            ['slug' => 'nagrevatel-chashek-cw-s', 'sku' => 'CW-S',
             'brand' => 'Carimali', 'title' => 'НАГРЕВАТЕЛЬ ЧАШЕК',
             'category' => 'superavtomaty', 'price' => 60459,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/nagrevatel-chashek-cw-s.jpg', 'sort' => 840,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'под заказ',
             'description' => 'под заказ'],
            ['slug' => 'modul-dlya-poroshkov', 'sku' => '–',
             'brand' => 'Carimali', 'title' => 'МОДУЛЬ ДЛЯ ПОРОШКОВ',
             'category' => 'superavtomaty', 'price' => 126000,
             'availability' => 'on_order', 'stock' => NULL,
             'image' => '/assets/shop/modul-dlya-poroshkov.jpg', 'sort' => 850,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Цвет черныйРазмеры (ШхВхГ) 144x717x436 мм (Armonia)144x818x436 мм (Optima)Масса 10 кг (Armonia) / 9 кг (Optima)Объем бункера для порошков 1,2 лНапряжение 220-240 В 50/60 ГцОсобенно',
             'description' => 'Цвет черныйРазмеры (ШхВхГ) 144x717x436 мм (Armonia)144x818x436 мм (Optima)Масса 10 кг (Armonia) / 9 кг (Optima)Объем бункера для порошков 1,2 лНапряжение 220-240 В 50/60 ГцОсобенности подсветка (Optima)'],
            ['slug' => 'kontsentrat-dlya-dekaltsinatsii-d11-d11', 'sku' => 'D11',
             'brand' => 'Carimali', 'title' => 'Концентрат для декальцинации D11',
             'category' => 'aksessuary', 'price' => 1218,
             'availability' => 'in_stock', 'stock' => NULL,
             'image' => '/assets/shop/kontsentrat-dlya-dekaltsinatsii-d11-d11.jpg', 'sort' => 860,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'Средство для очистки от накипи суперавтоматических кофемашин',
             'description' => 'Средство для очистки от накипи суперавтоматических кофемашин'],
            ['slug' => 'sredstvo-dlya-ochistki-molochnoy-sistemy-m11-m11', 'sku' => 'M11',
             'brand' => 'Carimali', 'title' => 'Средство для очистки молочной системы M11',
             'category' => 'aksessuary', 'price' => 1124,
             'availability' => 'in_stock', 'stock' => NULL,
             'image' => '/assets/shop/sredstvo-dlya-ochistki-molochnoy-sistemy-m11-m11.jpg', 'sort' => 870,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'в наличии',
             'description' => 'в наличии'],
            ['slug' => 'sredstvo-dlya-ochistki-molochnoy-sistemy-m14-m14', 'sku' => 'M14',
             'brand' => 'Carimali', 'title' => 'Средство для очистки молочной системы M14',
             'category' => 'aksessuary', 'price' => 1418,
             'availability' => 'in_stock', 'stock' => NULL,
             'image' => '/assets/shop/sredstvo-dlya-ochistki-molochnoy-sistemy-m14-m14.jpg', 'sort' => 880,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'в наличии',
             'description' => 'в наличии'],
            ['slug' => 'tabletki-dlya-chistki-zavarochnyh-uzlov-g31-g31', 'sku' => 'G31',
             'brand' => 'Carimali', 'title' => 'Таблетки для чистки заварочных узлов G31',
             'category' => 'aksessuary', 'price' => 2000,
             'availability' => 'in_stock', 'stock' => NULL,
             'image' => '/assets/shop/tabletki-dlya-chistki-zavarochnyh-uzlov-g31-g31.jpg', 'sort' => 890,
             'variant_group' => NULL, 'color' => NULL,
             'summary' => 'в наличии',
             'description' => 'в наличии'],
        ];

        foreach ($products as $p) {
            $p['product_category_id'] = $ids[$p['category']];
            unset($p['category']);
            Product::updateOrCreate(['slug' => $p['slug']], $p);
        }

        /* Каталог полностью описывается прайсом: позиции, которых в нём
           больше нет, удаляем, иначе в витрине останутся старые записи. */
        Product::whereNotIn('slug', array_column($products, 'slug'))->delete();
    }
}
